#CREATE DATABASE AKAMAI_TEST;
USE AKAMAI_TEST;

DROP TABLE IF EXISTS PEOPLE;

CREATE TABLE PEOPLE
(
    ID      SERIAL PRIMARY KEY,
    NAME   VARCHAR(100),
    SURNAME    VARCHAR(100),
	CITIZENSHIP VARCHAR(100)
);

INSERT INTO PEOPLE (NAME, SURNAME, CITIZENSHIP) VALUES ("John", "Smith", "Chad");

COMMIT;
